// Code generated from the Konnect AI Gateway available-policies endpoint.
// Refresh: GET /v1/ai-gateways/{id}/available-policies
// It records which entity scopes each policy (plugin) type may attach to,
// so the reverter can drop scope-incompatible policies during migration.
package policies

// PolicyScopes maps a plugin/policy type to the set of AI Gateway scopes it
// may be attached to (global, models, mcp-servers, agents, consumers,
// consumer-groups).
var PolicyScopes = map[string]map[string]bool{
	"ace":                            {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"acl":                            {"global": true},
	"acme":                           {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"ai-aws-guardrails":              {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-azure-content-safety":        {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-custom-guardrail":            {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-gcp-model-armor":             {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-lakera-guard":                {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-llm-as-judge":                {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-mcp-oauth2":                  {"global": true, "mcp-servers": true},
	"ai-prompt-compressor":           {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-prompt-decorator":            {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-prompt-guard":                {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-prompt-template":             {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-rag-injector":                {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-rate-limiting-advanced":      {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-request-transformer":         {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-response-transformer":        {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-sanitizer":                   {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-semantic-cache":              {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-semantic-prompt-guard":       {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"ai-semantic-response-guard":     {"consumer-groups": true, "consumers": true, "global": true, "models": true},
	"app-dynamics":                   {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"aws-lambda":                     {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"azure-functions":                {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"basic-auth":                     {"agents": true, "global": true, "mcp-servers": true},
	"bot-detection":                  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"canary":                         {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"confluent":                      {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"confluent-consume":              {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"correlation-id":                 {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"cors":                           {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"datadog":                        {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"datakit":                        {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"degraphql":                      {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"exit-transformer":               {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"file-log":                       {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"forward-proxy":                  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"graphql-proxy-cache-advanced":   {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"graphql-rate-limiting-advanced": {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"grpc-gateway":                   {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"grpc-web":                       {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"header-cert-auth":               {"agents": true, "global": true, "mcp-servers": true},
	"hmac-auth":                      {"agents": true, "global": true, "mcp-servers": true},
	"http-log":                       {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"injection-protection":           {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"ip-restriction":                 {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"jq":                             {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"json-threat-protection":         {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"jwe-decrypt":                    {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"jwt":                            {"agents": true, "global": true, "mcp-servers": true},
	"jwt-signer":                     {"agents": true, "global": true, "mcp-servers": true},
	"kafka-consume":                  {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"kafka-log":                      {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"kafka-upstream":                 {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"key-auth":                       {"agents": true, "global": true, "mcp-servers": true},
	"ldap-auth":                      {"agents": true, "global": true, "mcp-servers": true},
	"ldap-auth-advanced":             {"agents": true, "global": true, "mcp-servers": true},
	"loggly":                         {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"metering-and-billing":           {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"mocking":                        {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"mtls-auth":                      {"agents": true, "global": true, "mcp-servers": true},
	"oas-validation":                 {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"oauth2-introspection":           {"agents": true, "global": true, "mcp-servers": true},
	"opa":                            {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"openid-connect":                 {"agents": true, "global": true, "mcp-servers": true},
	"opentelemetry":                  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"post-function":                  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"pre-function":                   {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"prometheus":                     {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"proxy-cache":                    {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"proxy-cache-advanced":           {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"rate-limiting":                  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"rate-limiting-advanced":         {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"redirect":                       {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-callout":                {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-size-limiting":          {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-termination":            {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-transformer":            {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-transformer-advanced":   {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"request-validator":              {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"response-ratelimiting":          {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"response-transformer":           {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"response-transformer-advanced":  {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"route-by-header":                {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"route-transformer-advanced":     {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"saml":                           {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"service-protection":             {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"session":                        {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"solace-consume":                 {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"solace-log":                     {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"solace-upstream":                {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"standard-webhooks":              {"agents": true, "consumer-groups": true, "global": true, "mcp-servers": true, "models": true},
	"statsd":                         {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"syslog":                         {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"tcp-log":                        {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"tls-handshake-modifier":         {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"tls-metadata-headers":           {"agents": true, "global": true, "mcp-servers": true, "models": true},
	"udp-log":                        {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"upstream-oauth":                 {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true},
	"upstream-timeout":               {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"websocket-size-limit":           {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"websocket-validator":            {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"xml-threat-protection":          {"agents": true, "consumer-groups": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
	"zipkin":                         {"agents": true, "consumers": true, "global": true, "mcp-servers": true, "models": true},
}

// PolicyAllowedInScope reports whether a policy of the given plugin type may
// attach to the given scope. Unknown plugin types are allowed (the table
// only constrains types it knows about, so new/custom plugins pass through).
func PolicyAllowedInScope(pluginType, scope string) bool {
	scopes, ok := PolicyScopes[pluginType]
	if !ok {
		return true
	}
	return scopes[scope]
}
